print(abs(-10.96))
print(bin(2))
print(bytes(2))
print(chr(90))
print(complex(2, 3))
print(float(3))
print(int(3.9))
print(str(3.9))
print(str("3.9"))
print("Hello", input("Name"), input("Age"))
print(input("Enter Name:"))
